local ns = {}
assert(loadfile("addon/LycheeBlightfall_Core/Engine.lua"))("Test", ns)
local E, count = ns.Engine, 0
local function eq(actual, expected, label)
    assert(actual == expected, label .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual))
    count = count + 1
end
local opts = { textEnabled = true, soundEnabled = true, textLead = 3, soundLead = 3 }
local e = E.New()
e:Cast(E.DT, 0, "dt1")
eq(e:Update(0, opts, false).wake, 9, "fallback first signal")
e:Cast(47541, 2, "coil1")
e:Cast(47541, 2, "coil1")
eq(e.dtEnd, 16, "duplicate event must not extend twice")
eq(e:Update(9, opts, false).wake, 10, "silent candidate may move")
e:Cast(1242174, 9.5, "necrotic1")
eq(e.dtEnd, 17, "replacement coil extends")
local s = e:Update(11, opts, false)
eq(s.target, 14, "initial recommendation")
eq(s.show, true, "text at 3 sec")
eq(s.voice, true, "voice at 3 sec")
e:Cast(47541, 12, "coil2")
e:SetGCD(1, 12)
e:Cast(E.REAPER, 12.5, "sr1")
s = e:Update(13, opts, true)
eq(s.target, 18.5, "single-target SR branch can outlive DT")
eq(s.voice, nil, "voice once per cycle")
e:Cast(E.BLIGHTFALL, 14, "bf1")
eq(e:Update(14, opts, true), nil, "consumption clears")
e:Cast(E.DT, 30, "dt2")
e:Cast(E.REAPER, 33, "sr2")
e:SetGCD(1.25, 33)
s = e:Update(35.5, opts, true)
eq(s.target, 38.5, "SR expiry minus 2 GCDs")
eq(s.deadline, 41, "SR deadline")
e:Reset()
e:Cast(E.DT, 50, "dt3")
e:Cast(E.REAPER, 58, "sr3")
s = e:Update(59, opts, true)
eq(s.deadline, 66, "late SR follows SimC even beyond DT")
eq(s.target, 63, "stale haste falls back to 1.5s GCD")
eq(e:Update(66, opts, true), nil, "window expiration clears")
e:Cast(E.DT, 70, "dt4")
e:Cast(E.REAPER, 71, "sr4")
s = e:Update(79, opts, false)
eq(s.target, 82, "without Reaping ignore SR")
e:Reset()
e:Cast(E.DT, 100, "dt5")
local split = { textEnabled = true, soundEnabled = true, textLead = 1, soundLead = 3 }
s = e:Update(109, split, false)
eq(s.show, nil, "separate text lead")
eq(s.voice, true, "voice commits first")
eq(s.wake, 111, "wake for text")
e:Cast(47541, 110, "coil3")
s = e:Update(111, split, false)
eq(s.target, 113, "voice does not freeze later recommendation")
eq(s.show, nil, "text lead follows new target")
eq(s.voice, nil, "later text does not repeat voice")
s = e:Update(112, split, false)
eq(s.show, true, "text appears at updated lead time")
e:Cast(47541, 112.1, "coil4")
s = e:Update(112.1, split, false)
eq(s.show, true, "once visible text stays visible while time moves")
eq(s.target, 114, "visible countdown follows extension")
eq(e:SetGCD(0, 112), false, "idle GCD ignored")
eq(e:SetGCD(0/0, 112), false, "NaN GCD ignored")
e:Reset()
e:Cast(E.DT, 120, "dt6")
s = e:Update(140, opts, true)
eq(s, nil, "late timer cannot resurrect expired window")
e:Reset()
e:Cast(E.DT, 150, "dt7")
s = e:Update(159, {textEnabled=true, soundEnabled=false, textLead=3}, false)
eq(s.voice, nil, "muted cycle has no voice")
eq(s.show, true, "muted text works")
e:Reset()
e:Cast(E.DT, 200, "dt8")
e:Cast(E.REAPER, 202, "sr8")
s = e:Update(204, opts, true)
eq(s.target,207,"early SR caps suggestion")
e:Cast(47541,205,"coil8")
e:Cast(47541,206,"coil9")
s = e:Update(206, opts, true)
eq(s.target,207.5,"next spender GCD must finish inside SR")
eq(e:Update(210,opts,true),nil,"expired SR must not fall back to extended DT")
e:Cast(E.HEART,220,"heart1")
e:Cast(E.DT,221,"dt9")
e:Cast(E.REAPER,222,"sr9")
eq(e:Update(228,opts,true,true).target,233,"AOE ignores early SR expiry")
for i=1,8 do e:Cast(47541,228+i*0.5,"aoecoil"..i) end
s=e:Update(233,opts,true,true)
eq(s.target,237,"heart caps extended DT")
eq(s.deadline,240,"heart remembered when used before DT")
eq(s.reason,"heart","AOE heart reason")
eq(e:Update(240,opts,true,true).deadline,244,"expired heart no longer supplies an APL buff window")
e:Cast(E.DT,250,"dt10")
e:Cast(E.REAPER,251,"sr10")
eq(e:Update(253,opts,true,false).target,256,"single before transition")
eq(e:Update(254,opts,true,true).target,262,"AOE transition updates active countdown")
eq(e:Update(255,opts,true,true).voice,nil,"transition never repeats voice")
-- Public overlay observations are evidence of at most one charge, not a buff scan.
e:Reset()
e:Overlay(true, 300)
e:Overlay(true, 301)
eq(e.doomEnd,310,"duplicate redraw does not invent a fresh proc duration")
e:Cast(47541,302,"v1",true)
eq(e.strengthEnd,307,"observed proc plus coil infers five seconds before DT")
e:Cast(47541,303,"v2",true)
eq(e.strengthEnd,307,"ordinary coil does not refresh inferred strength")
e:Overlay(false,303.1)
eq(e.strengthEnd,307,"delayed overlay hide does not erase inferred strength")
e:Overlay(true,304)
e:Cast(207317,305,"v3",true)
eq(e.strengthEnd,310,"epidemic also consumes a new observed proc")
e:Cast(207317,305,"v3",true)
eq(e.strengthEnd,310,"duplicate cast cannot consume twice")
e:Cast(E.DT,306,"vdt",true)
eq(e.strengthEnd,310,"DT preserves already inferred strength")
eq(e:Update(306,opts,false,false,true).target,318,"early strength does not pull swallow before APL")
e:Reset()
e:Overlay(true,320)
e:Overlay(false,321)
e:Cast(47541,321.01,"hide-first",true)
eq(e.strengthEnd,nil,"hide before success stays uncertain, no invented strength")
e:Overlay(true,322)
e:Cast(47541,332,"expired-proc",true)
eq(e.strengthEnd,nil,"missing hide cannot keep proc alive past ten seconds")
e:Reset()
e:Overlay(true,340)
e:Cast(47541,341,"no-talent",false)
eq(e.strengthEnd,nil,"requires visceral talent")

-- Prepare before the APL threshold; never delay an eligible swallow for strength.
for _, aoe in ipairs({false,true}) do
    e:Reset()
    e:Cast(E.DT,400,"dt-prepare"..tostring(aoe))
    e:Cast(E.REAPER,407,"sr-prepare"..tostring(aoe)) -- both deadlines 415
    e:Overlay(true,409)
    s=e:Update(409,opts,true,aoe,true)
    eq(s.target,412,"preparation preserves the original APL target")
    eq(s.prepare,true,"show preparation only near the cast window")
    eq(s.voice,true,"voice remains three seconds before original target")
    s=e:Update(410.3,opts,true,aoe,true)
    eq(s.prepare,nil,"stop waiting while enough room remains to swallow")
    eq(s.target,412,"unconsumed proc cannot stall swallow")
    eq(s.voice,nil,"preparation timeout never repeats voice")
end
e:Reset()
e:Cast(E.DT,500,"dt-covered")
e:Cast(E.REAPER,507,"sr-covered")
e:Overlay(true,509)
e:Cast(47541,510.5,"consume-prep",true)
s=e:Update(510.5,opts,true,false,true)
eq(s.target,512,"consume then swallow on next GCD within SR")
eq(s.strengthCovers,true,"inferred strength covers recommended swallow")
eq(s.prepare,nil,"covered cast does not ask for a second spender")
e:Overlay(false,510.7)
e:Overlay(true,511)
eq(e:Update(511,opts,true,false,true).target,512,"new proc does not delay already covered swallow")
e:Reset()
e:Cast(E.DT,600,"dt-forgotten")
e:Overlay(true,609)
e:ForgetDoom()
eq(e:Update(609,opts,true,true,true).target,612,"unknown overlay falls back to original APL timing")
eq(e.strengthEnd,nil,"full reset removes old strength")
e:Reset()
e:Cast(E.DT,700,"dt-late-consume")
e:Cast(E.REAPER,712,"sr-late-consume")
e:Overlay(true,715.5)
eq(e:Cast(383269,716,"graveyard-consume",true),true,"replacement epidemic updates after DT has expired")
eq(e.strengthEnd,721,"replacement epidemic infers strength")
eq(e.dtEnd,715,"expired DT cannot be resurrected by a spender")
s=e:Update(716,opts,true,false,true)
eq(s.target,717.5,"post-DT strength inference still respects next GCD and SR")
eq(s.strengthCovers,true,"post-DT SR swallow has inferred strength coverage")

-- Across haste and both branches, preparation preserves the original APL
-- target, ends early enough for a spender, and never fabricates strength.
for _,gcd in ipairs({0.75,1,1.25,1.5}) do
    for _,aoe in ipairs({false,true}) do
        e=E.New()
        e:Cast(E.DT,800)
        e:Cast(E.REAPER,807)
        e:SetGCD(gcd,809)
        e:Overlay(true,809)
        for step=0,55 do
            local now=809+step/10
            s=e:Update(now,opts,true,aoe,true)
            assert(s.target == 815-2*gcd,"preparation changed the APL target")
            assert(not s.strengthCovers,"never invent strength while waiting")
            if now >= 815-3*gcd-0.2 then assert(not s.prepare,"preparation exceeded budget") end
        end
        eq(e:Update(815,opts,true,aoe,true),nil,"unconsumed proc cannot prolong the cycle")
    end
end
local ro = {reaperEnabled=true,textEnabled=true,soundEnabled=true,textLead=3,soundLead=3}
e=E.New()
eq(e:UpdateReaper(0,ro,true),nil,"no cycle")
e:Cast(E.DT,900,"new-dt")
s=e:UpdateReaper(900,ro,true,true)
eq(s.target,901.5,"without Heart immediate cue")
eq(s.show,true,"no invented three-second waiting period")
eq(s.voice,true,"immediate voice once")
eq(e:Update(910,ro,true).waitingReaper,true,"ST never swallows before actual Reaper")
e:Cast(47541,910,"new-coil")
eq(e:UpdateReaper(910,ro,true,true).target,901.5,"extension cannot postpone Reaper")
eq(e:UpdateReaper(910,ro,true,true).voice,nil,"one voice")
e:Cast(E.REAPER,911,"new-sr")
eq(e:UpdateReaper(911,ro,true),nil,"success cancels Reaper cue")
eq(e:Update(913,ro,true).target,916,"actual Reaper determines swallow")
e:Cast(47541,914,"new-coil2")
eq(e:Update(914,ro,true).target,916,"ST swallow does not chase DT")
e:Reset()
e:Cast(E.HEART,930,"heart-pre-dt")
e:Cast(E.DT,931,"heart-dt")
s=e:UpdateReaper(931,ro,true)
eq(s.target,941,"Heart activation plus eleven, not DT plus eleven")
eq(s.wake,938,"three-second lead")
eq(s.show,nil,"wait until lead")
s=e:UpdateReaper(938,ro,true)
eq(s.voice,true,"Heart voice at lead")
e:Cast(47541,939,"heart-coil")
eq(e:UpdateReaper(939,ro,true).target,941,"Heart schedule independent of extensions")
eq(e:Update(939,ro,true).waitingReaper,true,"no early ST swallow over delayed Reaper")
e:Cast(E.REAPER,942,"heart-sr")
eq(e:Update(945,ro,true).target,947,"late actual Reaper updates swallow")
eq(e:UpdateReaper(943,ro,true),nil,"manual Reaper cancels cue")
e:Reset()
e:Cast(E.DT,960,"aoe-dt")
eq(e:Update(969,ro,true,true).target,972,"AOE swallow retains DT rule")
eq(e:UpdateReaper(969,ro,true,true).target,961.5,"AOE uses same immediate Reaper cue")
e:Cast(E.HEART,961,"heart-after-dt")
eq(e:UpdateReaper(969,ro,true,true).target,972,"Heart observed after DT corrects target")
eq(e:UpdateReaper(969,ro,true,true).voice,nil,"target correction does not replay audio")
eq(e:UpdateReaper(970,ro,false),nil,"requires talents")
ro.reaperEnabled=false
eq(e:UpdateReaper(970,ro,true),nil,"independent toggle")
eq(e:Update(970,ro,true).waitingReaper,true,"mute cue does not change ST gameplay rule")
ro.reaperEnabled=true
eq(e:Update(975,ro,true),nil,"missed Reaper expires without false swallow")
e:Cast(E.DT,1000,"expired-heart-dt")
eq(e:UpdateReaper(1000,ro,true,true).target,1001.5,"old Heart cannot delay next cycle")
e:Cast(E.BLIGHTFALL,1001,"manual-bf")
eq(e:UpdateReaper(1001,ro,true),nil,"manual swallow clears both")
e=E.New()
e:Cast(E.DT,1100)
e:SetGCD(1,1100)
e:SetReaperReady(1100.3)
eq(e:UpdateReaper(1100,ro,true,true).target,1100.3,"use remaining GCD, not a fresh full GCD")
e:SetReaperReady(1102)
eq(e:UpdateReaper(1101,ro,true,true).target,1100.3,"later casts do not postpone first opportunity")
e:Reset()
e:Cast(E.DT,1120)
e:SetReaperReady(1120)
eq(e:UpdateReaper(1120,ro,true,true).target,1120,"public idle GCD means ready now")
e=E.New()
e:Cast(E.DT,1200)
eq(e:UpdateReaper(1200,ro,true,false).target,1207.01,"ST without Heart preserves SimC default")
eq(e:UpdateReaper(1204.01,ro,true,false).voice,true,"default ST three-second lead")
e:Cast(E.HEART,1205)
eq(e:UpdateReaper(1205,ro,true,false).target,1216,"Heart overrides default ST")
eq(e:UpdateReaper(1205,ro,true,true).target,1216,"Heart timing identical in AOE")
e=E.New()
eq(e:SetGCD(1,1300),true,"fresh one-second GCD changes estimate")
eq(e:GCD(1311),1.5,"old GCD falls back conservatively")
eq(e:SetGCD(1,1311),true,"same observed duration refreshes an expired estimate")
eq(e:GCD(1311),1,"refreshed duration is used")
eq(e:SetGCD(1,1312),false,"unchanged fresh GCD avoids redundant work")
print("Engine assertions passed: " .. count)
